### ISSUE TITLE
Method is Bradford, but matrix is Von Kries?

### ISSUE THREAD

**Issue by ghost** [EaryChow/Chromatic-Adaptation-Matrix-Generator#1]
```
method = 'Bradford'
matrix = colour.adaptation.matrix_chromatic_adaptation_VonKries(I_E, I_D65, method)
```
Is this possibly an overlooked mistake? It is confusing.

**Comment by EaryChow** [comment]
That's [the syntax of the `colour` package](https://colour.readthedocs.io/en/develop/generated/colour.adaptation.matrix_chromatic_adaptation_VonKries.html), not sure why either. But the end matrix matches the Bradford one listed on [this website](http://www.brucelindbloom.com/index.html?Eqn_ChromAdapt.html), so should be correct

**Comment by ghost** [comment]
Interesting. Well, if it works that way, I guess this issue can be closed.
